(()=>{const $=id=>document.getElementById(id);const DB='archiveMajor',STORE='photos';let db,items=[],files=[],viewerItems=[],viewerPos=0,filter='all',urls=[];
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function req(mode,fn){return new Promise((res,rej)=>{let r=fn(db.transaction(STORE,mode).objectStore(STORE));r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const all=()=>req('readonly',s=>s.getAll()),add=x=>req('readwrite',s=>s.add(x)),put=x=>req('readwrite',s=>s.put(x)),del=id=>req('readwrite',s=>s.delete(id));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function u(blob){let x=URL.createObjectURL(blob);urls.push(x);return x}function clearU(){urls.forEach(URL.revokeObjectURL);urls=[]}
function visible(zone){return items.filter(x=>x.show!==false&&(zone?x.zone===zone:true))}
function repeat(arr,min=10){if(!arr.length)return[];let out=[];while(out.length<min)out.push(...arr);return out}
async function refresh(){clearU();items=await all();render();renderManager();$('empty').classList.toggle('hidden',items.length>0)}
function card(it,i,cls='piece'){let b=document.createElement('button');b.className=cls;b.innerHTML=`<img src="${u(it.blob)}"><small>${String(i+1).padStart(3,'0')} ${esc(it.title)}</small>`;b.onclick=()=>openViewer(it);return b}
function render(){
 ['museumGallery','natureA','natureB','petsA','petsB','familyFeature','familyFilm','memoryGallery','tunnel','finaleCloud','heroFloat'].forEach(id=>$(id).innerHTML='');
 let m=visible('museum');m.forEach((it,i)=>$('museumGallery').appendChild(card(it,i)));
 let n=repeat(visible('nature'),12);n.forEach((it,i)=>{let c=card(it,i,'diag-card');(i%2?$('natureB'):$('natureA')).appendChild(c)});
 let p=repeat(visible('pets'),12);p.forEach((it,i)=>{let c=card(it,i,'polaroid');c.style.setProperty('--r',`${(i%5-2)*2.4}deg`);(i%2?$('petsB'):$('petsA')).appendChild(c)});
 let f=visible('family');if(f[0]){let x=document.createElement('button');x.className='family-large';x.innerHTML=`<img src="${u(f[0].blob)}">`;x.onclick=()=>openViewer(f[0]);$('familyFeature').appendChild(x)}repeat(f,12).forEach((it,i)=>$('familyFilm').appendChild(card(it,i,'film')));
 let mem=visible('memories');mem.slice(0,8).forEach((it,i)=>{let c=card(it,i,'scrap');c.style.setProperty('--r',`${(i%5-2)*3}deg`);$('memoryGallery').appendChild(c)});
 let feat=items.filter(x=>x.show!==false&&x.featured);let hero=(feat.length?feat:items.filter(x=>x.show!==false)).slice(0,3);hero.forEach((it,i)=>$('heroFloat').appendChild(card(it,i,'hero-card')));
 let tun=repeat(items.filter(x=>x.show!==false),9).slice(0,9);tun.forEach((it,i)=>{let c=card(it,i,'tunnel-card');c.dataset.i=i;$('tunnel').appendChild(c)});
 let fin=items.filter(x=>x.show!==false&&x.finale!==false);repeat(fin,14).slice(0,14).forEach((it,i)=>{let c=card(it,i,'final-card');let pos=[[5,18],[20,7],[40,15],[66,8],[82,22],[8,62],[25,72],[47,65],[70,73],[86,60],[16,38],[74,40],[37,82],[58,35]][i];c.style.left=pos[0]+'%';c.style.top=pos[1]+'%';c.style.animationDelay=`-${i*.35}s`;$('finaleCloud').appendChild(c)});
}
function renderManager(){
 let list=items.filter(x=>filter==='all'?true:filter==='hidden'?x.show===false:x.zone===filter);$('stats').textContent=`${items.length} รูป · ${items.filter(x=>x.show!==false).length} แสดง · ${items.filter(x=>x.show===false).length} ซ่อน`;$('managerGrid').innerHTML='';
 list.forEach(it=>{let d=document.createElement('div');d.className='manage-card'+(it.show===false?' hidden-photo':'');d.innerHTML=`<img src="${u(it.blob)}"><div class="manage-meta"><b>${esc(it.title)||'Untitled'}</b><span>${it.featured?'★ ':''}${it.zone}</span></div><div class="manage-controls"><button data-act="show">${it.show===false?'Show':'Hide'}</button><button data-act="feature">${it.featured?'★ Featured':'☆ Featured'}</button><select data-act="zone"><option value="museum">Museum</option><option value="nature">Nature</option><option value="pets">Pets</option><option value="family">Family</option><option value="memories">Memories</option></select><button data-act="finale">${it.finale===false?'Finale Off':'Finale On'}</button><button data-act="edit">Edit</button><button class="danger" data-act="delete">Delete</button></div>`;let s=d.querySelector('select');s.value=it.zone||'museum';d.querySelector('[data-act=show]').onclick=async()=>{it.show=it.show===false?true:false;await put(it);refresh()};d.querySelector('[data-act=feature]').onclick=async()=>{it.featured=!it.featured;await put(it);refresh()};s.onchange=async()=>{it.zone=s.value;await put(it);refresh()};d.querySelector('[data-act=finale]').onclick=async()=>{it.finale=it.finale===false?true:false;await put(it);refresh()};d.querySelector('[data-act=edit]').onclick=async()=>{let t=prompt('ชื่อภาพ',it.title||'');if(t!==null){it.title=t;let m=prompt('วันที่ / ปี',it.meta||'');if(m!==null)it.meta=m;await put(it);refresh()}};d.querySelector('[data-act=delete]').onclick=async()=>{if(confirm('ลบรูปนี้ถาวรหรือไม่?')){await del(it.id);refresh()}};$('managerGrid').appendChild(d)})
}
function modal(id,on=true){$(id).classList.toggle('open',on)}$('addBtn').onclick=()=>modal('uploadModal');$('emptyAdd').onclick=()=>modal('uploadModal');$('settingsBtn').onclick=()=>{renderManager();modal('settingsModal')};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal(x.dataset.close,false));document.querySelectorAll('.modal').forEach(x=>x.onclick=e=>{if(e.target===x)x.classList.remove('open')});
$('files').onchange=()=>{files=[...$('files').files].filter(f=>f.type.startsWith('image/'));$('previews').innerHTML='';files.slice(0,15).forEach(f=>{let im=document.createElement('img'),x=URL.createObjectURL(f);im.src=x;im.onload=()=>URL.revokeObjectURL(x);$('previews').appendChild(im)})};
$('uploadForm').onsubmit=async e=>{e.preventDefault();if(!files.length)return alert('เลือกรูปก่อน');for(let f of files)await add({blob:f,title:$('title').value.trim(),meta:$('meta').value.trim(),zone:$('zone').value,display:$('display').value,featured:$('featured').checked,finale:$('inFinale').checked,show:true,createdAt:Date.now()});files=[];$('uploadForm').reset();$('previews').innerHTML='';modal('uploadModal',false);refresh()};
$('filters').onclick=e=>{let b=e.target.closest('button');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===b));renderManager()};
$('previewBtn').onclick=()=>{document.body.classList.toggle('preview-mode');$('previewBtn').textContent=document.body.classList.contains('preview-mode')?'✎ Edit mode':'👁 Preview'};
function openViewer(it){viewerItems=items.filter(x=>x.show!==false);viewerPos=Math.max(0,viewerItems.findIndex(x=>x.id===it.id));showViewer();$('viewer').classList.add('open')}function showViewer(){let it=viewerItems[viewerPos],x=URL.createObjectURL(it.blob);$('viewerImg').onload=()=>URL.revokeObjectURL(x);$('viewerImg').src=x;$('viewerNo').textContent=String(viewerPos+1).padStart(3,'0');$('viewerTitle').textContent=it.title||'';$('viewerMeta').textContent=it.meta||''}$('viewerClose').onclick=()=>$('viewer').classList.remove('open');$('viewerPrev').onclick=()=>{viewerPos=(viewerPos-1+viewerItems.length)%viewerItems.length;showViewer()};$('viewerNext').onclick=()=>{viewerPos=(viewerPos+1)%viewerItems.length;showViewer()};
let t=0;function animate(){t+=.008;document.querySelectorAll('.tunnel-card').forEach((c,i)=>{let a=t+i*.7,z=(Math.sin(a)+1)/2,x=Math.cos(a*.7+i)*innerWidth*.24,y=Math.sin(a*.9+i)*innerHeight*.18,s=.45+z*.8;c.style.transform=`translate(-50%,-50%) translate3d(${x}px,${y}px,${z*350}px) rotate(${Math.sin(a)*6}deg) scale(${s})`;c.style.zIndex=Math.round(z*100)});requestAnimationFrame(animate)}animate();
openDB().then(refresh).catch(e=>{console.error(e);alert('ไม่สามารถเปิดระบบจัดเก็บรูปได้')})})();